- .travis.yml
- README.md
- config/application.php
- ruleset.xml
- web/app/mu-plugins/bedrock-autoloader.php
- web/index.php
> Add PHPCS and Travis

- web/app/mu-plugins/bedrock-autoloader.php
> Fix mu-plugins not shown in multisite setup

- web/app/mu-plugins/register-theme-directory.php
Added plugin meta for nicer output in Must use plugin listing.
> Added plugin meta for nicer output

- config/application.php
- config/environments/development.php
- config/environments/production.php
- config/environments/staging.php
No point in repeating these settings in every env config since it's all the same, so we'll move them to `application.php`.
> DRY up environment configs

- composer.lock
https://github.com/composer/composer/blob/e0ce559838e0cd7a01404b4b85d2a2768d0ec1e9/src/Composer/Command/UpdateCommand.php#L133
> Updates lockfile for latest composer

- CHANGELOG.md
- composer.json
- composer.lock
PHP 5.4 EOL is in 10 days: http://php.net/supported-versions.php
> Bump minimum required PHP version to 5.5

- .env.example
Help the user remember they need to add the salts. See: #207
> Add placeholder salts to remind they are needed

- README.md
> Add info about salts

- CHANGELOG.md
- README.md
- composer.json
- composer.lock
https://github.com/roots/wp-password-bcrypt
> Add wp-password-bcrypt plugin for secure passwords

- README.md
- composer.json
PHP 5.5 is no longer supported: http://php.net/supported-versions.php
> Bump requirements to PHP 5.6

- README.md
This is just a small doc improvement:
* Show more explicit usage of `composer create-project` command
* Show more detailed usage and installation of aaemnnosttv/wp-cli-dotenv-command
* Abbreviated a couple of links  to make the text easier to edit
> Update instructions for generating salts

- CHANGELOG.md
- composer.json
- composer.lock
> Update to WordPress 4.9.7

- .gitattributes
- dependencies.yml
initial config for https://www.dependencies.io/ to support auto-updating bedrock's PHP dependencies
> Config for Dependencies.io

- CHANGELOG.md
- composer.json
- composer.lock
ref https://github.com/roots/wordpress
ref https://github.com/roots/wordpress/tree/src
@austinpray did a lot of awesome work this weekend and will be writing a post about these changes up on the blog shortly
> Update to WordPress 5.0, switch from from johnpbloch/wordpress to roots/wordpress

- dependencies.yml
maybe this will prevent things like #399 #396 #394 #393 #392?
ref https://www.dependencies.io/docs/dependencies-yml/filtering-updates/
> Dependencies.io: Filter updates

- config/application.php
> Revert "Adjust logic to handle empty DB_PREFIX"

- composer.json
- composer.lock
- Bump `composer.lock`
- Enable `sort-packages` and [`optimize-autoloader`](https://getcomposer.org/doc/articles/autoloader-optimization.md)
> Better default composer options

- composer.json
- phpcs.xml
> Revert "Use inline phpcs rules instead of phpcs.xml"

- composer.json
> Stop auto sorting the packages

- .env.example
> Double quote to interpolate WP_SITEURL

- CHANGELOG.md
- composer.json
- composer.lock
See:
- https://github.com/outlandishideas/wpackagist/pull/311
- https://github.com/composer/composer/pull/8755/
- https://php.watch/articles/composer-2
> Composer: Add `only` option to wpackagist.org repository

- README.md
> try a bigger logo size

- composer.json
- composer.lock
- config/application.php
> Upgrade `oscarotero/env` to `^2.0`

- .gitattributes
`.github` folder should not be in created projects
> export-ignore github workflows

- .gitignore
https://github.com/roots/sage/pull/2837
> Ignore Acorn cache dir

- .gitignore
- CHANGELOG.md
- composer.json
- composer.lock
- phpcs.xml
https://wordpress.org/news/2022/11/misha/
> ➕ Replace twentytwentytwo with twentytwentythree

- .gitignore
- composer.json
- composer.lock
- phpcs.xml
https://make.wordpress.org/core/2023/08/24/introducing-twenty-twenty-four/
> ➕ Replace twentytwentythree with twentytwentyfour

- .github/workflows/ci.yml
- composer.json
- composer.lock
https://www.php.net/supported-versions.php
https://endoflife.date/php
Ref https://github.com/roots/bedrock/pull/665
Ref https://github.com/roots/bedrock/pull/746
> 🔧 Bump requirements to PHP 8.1

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .github/workflows/integration.yml
> 💚 Fix integration test
