roots/bedrock

composer.json, composer.lock
Bedrock was still referencing WordPress 4.1 in the composer.lock file. This updates the hash to point to version 4.1.1
=> Fix reference to WordPress 4.1.1

composer.json
This commit uses the ~ operator on composer requirements so that composer upgrade grabs the latest bugfixes etc...
=> use ~ operator on composer requirements

config/application.php, web/index.php
This should make the overall bedrock experience a bit faster. See [this StackOverflow thread](http://stackoverflow.com/questions/2749416/is-there-any-difference-between-dir-and-dirname-file-in-php) on why this is better.
As I see in `composer.json`, minimum PHP version supported is 5.4, so this should work OK.
=> Switch to __DIR__ instead of dirname()

config/application.php
Couple of minor tweaks here in `application.php`.
Using short array syntax per style guidelines, as well as short ternary syntax for getenv defaults.
Checked with codesniffer.
=> Cleaner syntax

composer.json
PSR-0 is deprecated:
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md
We should use PSR-4, the recommended alternative.
=> PSR-0 Deprecation: use PSR-4

composer.json, composer.lock, config/application.php
Following my testing on roots/bedrock-ansible#254, I discovered that dotenv recently got rewritten as v2, with a better support of loaded values (see linked PR comment), and is now PSR compliant.
=> Update Dotenv to version 2, which produce better results.

config/application.php
Fixes a crash in Dotenv required which expects a valid Loader instance in $this->loader in `vendor/vlucas/phpdotenv/src/Dotenv.php` on line `83`
=> Only call required if .env file exists

.gitignore
In my experience, I haven't had a situation where I had a mu-plugin in the root of the mu-plugins directory that I would want to ignore as these are almost always self-created.  Sub directories, however, are usually ok to ignore as a rule, as those can be packages, which should be ignored.  Since packages can't be installed into the root, without some kind of custom installer, it makes more sense I think to have it like this.  Of course there could be sub-directories there that you may not want to ignore, and then in those situations, it makes perfect sense to add an exception in the ignore.
From a workflow perspective, it seems unintuitive to me that if I want to add an mu-plugin of my own in the root, that I should then need to add it to the gitignore whitelist.
**TL;DR**
This changes …
=> Simplify gitignore for mu-plugins

config/application.php
This allows better control via configuration management like Trellis.
Also change the default to `false`. This setting requires external server configuration for cron to work and since Bedrock is a standalone boilerplate, we shouldn't require that by default.
=> Set DISABLE_WP_CRON from env var

web/app/mu-plugins/bedrock-autoloader.php
`get_mu_plugins()` is being called with an argument, but this function does not accept one. I checked back to 3.0.0 when it was introduced and it doesn't appear this API call ever accepted an argument.
This PR simply removes the argument from the call for clarity's sake.
=> In the autoloader, remove argument from call to get_mu_plugins()

.env.example
Since v2.0, Dotenv has allowed for [nested variables](https://github.com/vlucas/phpdotenv/blob/91064290f5b53a09bdff1b939d7f69fb0e7531b5/README.md#nesting-variables).
Thoughts on using this?  It seems kind of silly to have to duplicate manually.
An alternative might be adding a conditional in `config/application.php` where, if `WP_SITEURL` isn't defined, it defaults to `WP_HOME/wp`, and then we could `dotenv->require()` one less env var at the same time?
=> Used nested WP_HOME in WP_SITEURL

config/application.php
In Bash, environment variable is always a string (which is what getenv() returns).
Because of the way this constant is checked in WP:
`if ( defined('DISABLE_WP_CRON') && DISABLE_WP_CRON )`,
setting `DISABLE_WP_CRON=false` would resolve to true.
This approach should be more predictable
=> env variables are strings

CHANGELOG.md, composer.json, composer.lock, config/application.php
See https://github.com/roots/bedrock/pull/229 for background.
The `env` function from https://github.com/oscarotero/env handles simple coercions for values like 'True' (`true`) which is needed.
=> Use oscarotero/env instead of `getenv`

.env.example
If we use the Salt function on api.wordpress.org, the keys will usually contain spaces. To avoid the `'Dotenv\Exception\InvalidFileException' with message 'Dotenv values containing spaces must be surrounded by quotes.'`, we should instruct users to quote their keys.
=> Instruct users to quote salts in .env.example

.gitattributes
When composer installs a stable version of a project it will use the
`dist` as the default.
This `.gitattributes` file excludes several files and directories from
being exported to the dist zip file.
This should make it easier for users to get started, since they don't
have to "clean up" the generated directory.
=> Ignore irrelevant files when installing via Composer

web/app/mu-plugins/bedrock-autoloader.php
As it is, the scope for an autoloaded mu-plugin is unnecessarily polluted.
I'm using this simple test plugin as an example here:
```php
// web/app/mu-plugins/test/test.php
<?php
/**
* Plugin Name: TEST
*/
var_dump(get_defined_vars());
die;
```
When we run this, we get quite a few results:
```
array(2) {
["plugin_info"]=>
array(11) {
["Name"]=>
string(4) "TEST"
["PluginURI"]=>
string(0) ""
["Version"]=>
string(0) ""
["Description"]=>
string(0) ""
["Author"]=>
string(0) ""
["AuthorURI"]=>
string(0) ""
["TextDomain"]=>
string(0) ""
["DomainPath"]=>
string(0) ""
["Network"]=>
bool(false)
["Title"]=>
string(4) "TEST"
["AuthorName"]=>
string(0) ""
}
["plugin_file"]=>
string(13) "test/test.php"
}
```
Not only that but if we dump `$this` from our test plugin we get:
``` …
```
=> Isolate scope for autoloaded mu-plugins

config/application.php
In my enormous amount of spare time, I've been working on a side project where I'm working on integrating best practices throughout a WP project.
It seems like a more sensible default for a site would be to default to production, rather than development. Development has all errors being displayed, amongst some other things. It's rather pedantic, but if a user forgets to set this for some reason, the safer option would be production rather than development
=> Production environment by default

README.md, composer.json
We know that everyone going to copy ```.env.example``` and create a ```.env``` so why not auto create this file.
This script will run only when someone​ use ```composer create``` command.
=> Auto create .env on composer create

composer.json, composer.lock
Closes https://github.com/roots/bedrock/issues/323
Bumping [oscarotero/env](https://github.com/oscarotero/env) to a newly released version would help with possible cases where the `env()` function wouldn't work in cases where server has disabled `putenv()` + `getenv()` commands.
=> Bump oscarotero/env

web/app/mu-plugins/disallow-indexing.php
was talking to a dev who used bedrock in development but not in production. but they inadvertently kept the mu-plugin to disable indexing by search engines. oops.
with this pr, the plugin will have no effect if `WP_ENV` isn't defined
=> Check if WP_ENV is defined in disallow-indexing

CHANGELOG.md, composer.json, composer.lock
I thought of adding [this](https://gist.github.com/knowler/41d45ed19812a60453a44cbab1be9964) first, but that'd be evil 😄.
Edit: actually, it looks like they've limited the audience for the callout. It doesn't show up in production.
=> Update to WordPress 4.9.8

composer.lock
Changes lockfile when you use update --prefer-dist 
shrug.jpg
=> --prefer-dist on roave/security-advisories

config/application.php
Hello,
It'd be great if HTTPS would be working behind a reverse proxy, which is very common when using a PaaS or a WAF, or any decent cloud providers.
https://codex.wordpress.org/Function_Reference/is_ssl#Notes
Since it's a condition, it does not harm existing wordpress installations.
=> Detect HTTPS if wordpress is behind a reverse proxy

.env.example, README.md, config/application.php
Hello,
As mentionned on the .README, 
> Bedrock is inspired by the [Twelve-Factor App](http://12factor.net/) methodology
So I was surprised, during my 120+ Wordpress migration plan to add the same snippet over and over again to allow to use a DSN instead of all the random legacy Wordpress variables (`DB_NAME`, `DB_USER`...).
The 12Factor app is clearly in favor of using DSN: https://12factor.net/backing-services.
Also, when using a recent cloud provider, or PaaS provider, the often expose the database through a DSN (since they follow 12Factor App methodology too).
For those reading the PR and who don't know what a [DSN](https://en.wikipedia.org/wiki/Data_source_name) is, it's a string containing the connection information. Ex: 
``` …
```
=> Allow to use a database DSN instead of all the database variables

.env.example, README.md, config/application.php
Figured I'd propose this change as the implementation is still early so despite being a "breaking change" – very few would be affected.
- Change `DATABASE_URL` to `DB_URL` to remain uniform with the other database variables
- Improve phrasing on the README and `.env.example` DocBlock
- Minor golfing / cleanup on how the DSN is handled in `application.php`
- Apparently editorconfig found some trailing whitespace in the README 🙀
=> Make DSN implementation more uniform

config/application.php
The DSN support added last week broke all of my sites running Bedrock in PHP5. I see that PHP5 support has been dropped from the project a few weeks ago, but for the sake of argument, the next line below is using syntax that is compatible.
=> Swap Usage of PHP 7 Null Coalesce Operator 

web/app/mu-plugins/bedrock-autoloader.php
This fixes an issue where the `bedrock_autoloader` option is set but the number of plugins differs. I ran into this issue when moving a plugin from `plugin` to `mu-plugin` and deploying to a remote server. 
I haven't been able to recreate this in a reliable way but having ran into this issue a couple of times on different servers I figured I'd propose my fix.
Basically $cache will not evaluate to `false` because it will be set to an array looking like this:
```
array(
'plugins' => array(),
'count' => 0,
);
```
This fixed it for me.
I created the issue in the wrong project. And instead of spamming new issue here you can read my original issue on the Trellis-project https://github.com/roots/trellis/issues/1022.
If you want me to open issue here anyway I can do it.
=> Fix issue with bedrock_autoloader option

wp-cli.yml
This configures `wp server` to use the proper webroot by default, so that you don't need to run `wp server --docroot=web`.
=> Configure wp-cli so that `wp server` uses correct webroot

config/application.php
I had a site that was not using prefixes on the database. Bedrock does not support this and evaluates `DB_PREFIX=''` as `false`.
=> Adjust logic to handle empty DB_PREFIX

config/environments/development.php
This was brought up in Slack. Not only is the error handler somewhat redundant, it is also producing some not so wanted behavior such as sending out emails to the admin email when an error occurs which could be rather intrusive if you have a mail server present on the development environment as it could potentially push an email to a client, etc.
=> Disable WordPress' built-in fatal error handler on development

web/app/mu-plugins/bedrock-autoloader.php
Since the autoloader is singeleton there is no reason to keep the static variables
=> Remove unnecessary static variables

.gitignore
This add `debug.log` file to `.gitignore`
=> Ignore debug.log

config/application.php, config/environments/development.php
`Uncaught TypeError: ini_set() expects parameter 2 to be string, int given`
https://www.php.net/manual/en/function.ini-set.php
=> ini_set() expects parameter 2 to be string, int given

.gitattributes
With #455 revealing that `phpcs.xml` is actually used by people leading to #461 – it seems like it would be ideal if `phpcs.xml` is pulled down when creating a project.
=> Remove phpcs.xml from .gitattributes

.env.example, README.md
Issue #469 points out that characters following a `#` in the value of an unquoted string in an `.env` file will be parsed as a comment, which is demonstrably undesirable. https://github.com/vlucas/phpdotenv/issues/354 confirms that this is the intended behavior of the library Bedrock uses and that quoting the string in question solves the problem, but the Bedrock README doesn't make any mention of this and the example `.env` uses quotes only on the WordPress keys, implying that other values may not need quoting. 
For this PR I've wrapped all values in the example `.env` with single quotes. I've only used single quotes to match what the Roots key generator uses and the quotes already present in `.env.example`. So far as I can tell, dotenv considers `'` and `"` the same for the purposes of …
=> Document and suggest quoting .env var values

composer.json, composer.lock, config/application.php
Ref #484
`vlucas/phpdotenv` > 4.0.0 has a breaking change as the initialization method has been split up and the old method has been removed.
The new methods require you to specify if the env definitions are immutable or mutable. 
This PR addresses this incompatibility by implementing the new `Dotenv::createImmutable` method. I don't think Bedrock is doing any overloading, so this is probably the better practice.
=> Upgrade vlucas/phpdotenv to ^4.0.1 & fix breaking change

config/application.php, web/app/mu-plugins/bedrock-autoloader.php, web/app/mu-plugins/disallow-indexing.php, web/app/mu-plugins/register-theme-directory.php, web/index.php
- **Opinionated change**: Clean up existing docblocks as well as make them more uniform across the entire package.
=> Clean up docblocks & commenting

.env.example, CHANGELOG.md, config/application.php
See: https://github.com/roots/trellis/pull/1160
=> Add `WP_DEBUG_LOG`

CHANGELOG.md, web/app/mu-plugins/bedrock-autoloader.php
fix(mu-plugins): A more sane fix for #510
=> chore(mu-plugins): Bump bedrock-autoloader version

.circleci/config.yml
- use offical CircleCI [PHP orb](https://circleci.com/orbs/registry/orb/circleci/php)
- use offical CircleCI [next-gen docker images](https://circleci.com/docs/2.0/circleci-images/#next-generation-convenience-images)
- use [`matrix`](https://circleci.com/docs/2.0/configuration-reference/#matrix-requires-version-21)
Dropped PHP 7.1 testing because of https://github.com/CircleCI-Public/cimg-php/issues/1#issuecomment-545532033
> Is it possible to add back PHP 7.1 test with the new php orb?
Yes. Let me know if we need it.
Not much difference actually.
Downloading the docker image, which ranging from 3 to 40 second depends whether the CircleCI instance has the docker layer cached, makes up the most of the build time.
With CircleCI pushing its new docker images forward, I expect the cache hit …
=> CircleCI: Use offical CircleCI PHP orb and next-gen docker images

composer.lock
ref https://github.com/roots/wordpress-core-installer/issues/4#issuecomment-716227485
Should be able to `composer create roots/bedrock` under both composer 1 and 2
Created project should boot an instance of WordPress just fine.
=> Bump roots/wordpress-core-installer for composer 2

composer.json, composer.lock, config/application.php
This PR upgrades `vlucas/phpdotenv` to the current version of `5.2`. As in https://github.com/roots/acorn/pull/74#issuecomment-734279706 mentioned, Laravel 8.x and therefor `roots/acorn` with support for Laravel 8.x will need an upgrade of the package and [minor migration changes](https://github.com/vlucas/phpdotenv/blob/master/UPGRADING.md).
=> Upgrade to vlucas/phpdotenv:5.2

config/application.php
We more often than not, like to limit the number of post revisions in our various environments, in order to contain the size that the database can grow to (one client's wp_posts table is currently up to 200MB, after only 3 months of UAT).
Providing the ability to define this simply, via the `.env` will make the process of defining this per environment, much more convenient.
By default, it remains as `true` so not to effect the default behaviour.
=> Add WP_POST_REVISIONS as an option

CHANGELOG.md, config/application.php
Suggested by @TangRufus in https://github.com/roots/bedrock/pull/586#issuecomment-816428722
If `.env.local` exists, any values will override and take precedence over those in `.env`. This is meant for local development only. Note: `.env.local` is already gitignored 
There's been some other related proposals in https://github.com/roots/bedrock/pull/587 and https://github.com/roots/bedrock/pull/586 but this one is simpler since it's additive only. We're just supporting a common workflow without breaking anything.
=> Support .env.local config override

.env.example, CHANGELOG.md, config/application.php, config/environments/development.php
Setting WP_DEBUG_LOG to `true` will cause WP to automatically log debug output to <WP_CONTENT>/debug.log (so app/debug.log). This is a sensible default.
See: https://wordpress.org/support/article/debugging-in-wordpress/#wp_debug_log
=> fix(debug-log): WP_DEBUG_LOG should be `true` by default

config/application.php
For reference: [b2781b8#commitcomment-54196503](https://github.com/roots/bedrock/commit/b2781b890e5f988f847e716e6abbc48e34c3cc5c#commitcomment-54196503)
I also removed this `if`
https://github.com/roots/bedrock/blob/master/config/application.php#L33
If .env file is not present a `\Dotenv\Exception\InvalidPathException` will be raised.
Fixes #601
=> Fixes #601 - .env.local failed to open stream php warning

.github/workflows/ci.yml, CHANGELOG.md, README.md, composer.json, composer.lock
PHP 7.3 EOL is 2021-12-06
https://www.php.net/supported-versions.php
=> Bump requirements to PHP 7.4

composer.json
We require two composer plugins. As of Composer v2.2.0, the default behavior is that [plugins must be explicitly allowed](https://getcomposer.org/doc/06-config.md#allow-plugins).
=> chore(deps): allow required composer plugins

CHANGELOG.md, composer.json, composer.lock
https://wordpress.org/news/2022/01/josephine/
=> chore(deps): Bump roots/wordpress to 5.9

README.md
As of WordPress 6.0, the behavior changed so add a note about it per https://github.com/roots/bedrock/issues/640.
=> doc: instructions for installing "source" packages

.github/workflows/ci.yml
Fixed typo in input for [shivammathur/setup-php](https://github.com/shivammathur/setup-php), must be [`php-version`](https://github.com/shivammathur/setup-php/tree/2.21.2#php-version-required) instead of `php_version`.
This typo prevented the action from detecting the matrix job's PHP version, installing the latest version of PHP instead.
Renamed matrix job configuration from `php_version` to `php-version` for consistency with action.
[![Screen capture of Setup PHP step of Build 7.4 of Run 8116757560 warning of unexpected input 'php_version' and installation of PHP 8.1.19 instead of PHP 7.4](https://user-images.githubusercontent.com/29353/189196853-b485ce4b-3aad-46d0-b4fc-dbc062746e62.jpg)](https://github.com/roots/bedrock/runs/8116757560?check_suite_focus=true#step:3:1)
=> Fix GitHub Actions CI Workflow

config/application.php
Hi, noticed that the default setup for application.php does not allow to turn off revisions through the value of `WP_POST_REVISIONS`. Setting either false or 0 results on enabling the feature completely, which is pretty confusing.
=> fix: can disable revisions by setting false or 0

config/application.php
Passing the `DB_SSL` environment variable can trigger the use of SSL client connections to MySQL. This is especially useful for remote/managed databases where SSL certificates are required.
Pulled from https://discourse.roots.io/t/roots-with-digital-ocean-managed-databases/16582.
=> Added support for SSL database connections

.github/workflows/ci.yml, README.md, composer.json, composer.lock
https://www.php.net/supported-versions.php
https://endoflife.date/php
I'd prefer to bump this to PHP 8.1, considering active support for PHP 8.0 ended on 2022-11-26, but WordPress & WP-CLI _still_ don't fully support it at this time
Ref **https://roots.io/wordpress-php-8-1-support-not-found/**
Ref https://core.trac.wordpress.org/ticket/54504 (coming in WordPress 6.2)
Ref https://github.com/wp-cli/wp-cli/issues/5623
=> 🔧 Bump requirements to PHP 8.0

config/application.php
This PR implements proposal suggested by @swalkinshaw: https://github.com/roots/bedrock/pull/627#issuecomment-1329295366
=> Support WP_ENVIRONMENT_TYPE

config/application.php
In `production` environment `.env` files are never used, so we don't need to create `Dotenv` instance if `.env` file not exists.
=> Don't instantiate Dotenv if .env file not exists

composer.json
`.env.example` is just an example and doesn't contain useful defaults. Copying this file can be confusing since it needs to be edited regardless. By not copying this file, we'll surface errors of missing config values sooner since they'll be no default values.
This is an alternative to https://github.com/roots/bedrock/pull/587 and https://github.com/roots/bedrock/pull/586
Docs PR: https://github.com/roots/docs/pull/476
=> Remove post install .env copy

.github/workflows/ci.yml
This PR Fixes warnings in CI action.
Ref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> fix: The `set-output` command is deprecated and will be disabled soon.

config/application.php
This has been brought up a few times internally and in [the comments in this repo](https://github.com/roots/bedrock/pull/563#issuecomment-953925928).
Here's an example scenario in a multithreaded environment:
> Putenv and Getenv are not thread-safe. This is probably the cause of your issue.
> 
> What happens is the following:
> 1st request: variables are not there -> load
> 2nd request: variables are there -> do not load
> 1st request: ends, cleans up variables
> 2nd request: use variable -> does not exist anymore, cleaned up by 1st request
h/t https://github.com/vlucas/phpdotenv/issues/248#issuecomment-450903446
The rest of the PHP community has largely moved away from `putenv()` and `getenv()` due to this limitation, and it's the reason why vlucas/phpdotenv moved away from it as a …
=> 💥 use `Dotenv::createImmutable()`

wp-cli.yml
Reverts roots/bedrock#636
See https://github.com/roots/bedrock/commit/566407b9df7a8a7ab7c67f410ac8a931fa676410#commitcomment-141640789
=> Revert "Require project autoloader in wp-cli.yml"

web/app/mu-plugins/bedrock-autoloader.php
https://github.com/roots/bedrock/blob/8df74d1dfdd60953db939ac7cbd3d134310aa863/composer.lock#L342-L343
Maybe there is a better way of fetching version from lockfile or adding it to roots/bedrock-autoloader per default. But until then...
=> Display correct bedrock-autoloader version

.devcontainer/.env.example, .devcontainer/.gitignore, .devcontainer/Dockerfile, .devcontainer/config/nginx.conf, .devcontainer/config/php.ini, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .gitattributes, .github/workflows/integration.yml
This PR adds a dev container and uses it for the integration test
=> 🔧 Add dev container

config/application.php
This PR sets `CONCATENATE_SCRIPTS` to false by default which prevents WordPress from concatenating scripts
Ref https://discourse.roots.io/t/upstream-timed-out-for-load-styles-php/26973
=> 🔧 Disable script concatenation by default

config/application.php
Updates to using a custom repository for `Dotenv` instead of the default which includes `ServerConstAdapter`.
The new custom repository *only* includes `EnvConstAdapter`.
The `$_SERVER` superglobal often gets dumped into logs or into monitoring services so it's better for security to avoid populating it with secrets contained in `.env`.
*Note*: this *could* be a breaking change for some users, but we at least need to ensure it's not breaking in the normal case.
Close #474
=> Don't leak env values into `$_SERVER`

.gitignore
auth.json is used to authenticate requests to private composer repsitories and should never be committed to the repo.
=> Added auth.json

README.md, composer.json, composer.lock
WP 6.8 has been released (April 15 2025). This version now ships with bcrypt password hashing, meaning the Roots team are [sunsetting roots/wp-password-bcrypt](https://github.com/roots/wp-password-bcrypt/pull/52).
See: 
- https://roots.io/sunsetting-wp-password-bcrypt-with-wordpress-6-8/
- https://make.wordpress.org/core/2025/02/17/wordpress-6-8-will-use-bcrypt-for-password-hashing/
- https://wordpress.org/download/releases/6-8/
=> Remove roots/wp-password-bcrypt 

config/application.php
This fixes the following phpstan error regarding the type of $webroot_dir declared in the phpdoc :
```
PHPDoc tag @var with type string is not subtype of native type  
non-falsy-string.                                               
🪪  varTag.nativeType        
```
=> fix: $webroot_dir phpdoc type
